name: value-gate
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check PR body for required sections
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "$BODY" | grep -qi "## User Value" || (echo "❌ Missing: User Value" && exit 1)
          echo "$BODY" | grep -qi "## Hypothesis" || (echo "❌ Missing: Hypothesis" && exit 1)
          echo "$BODY" | grep -qi "## Metrics Affected" || (echo "❌ Missing: Metrics" && exit 1)
          echo "$BODY" | grep -qi "## Rollback Plan" || (echo "❌ Missing: Rollback" && exit 1)
          echo "✅ Value Gate passed"
